name: HN Host Auto Task

on:
  workflow_dispatch:
  schedule:
    - cron: '20 2 * * *'

permissions:
  contents: write

jobs:
  run-automation:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout public repo
        uses: actions/checkout@v4

      - name: Checkout private code
        uses: actions/checkout@v4
        with:
          repository: hhup365/Test-Hn-host
          token: ${{ secrets.GH_PAT }}
          path: private_repo

      - name: Merge private code into workspace
        run: |
          rsync -a --exclude='.git' private_repo/ ./
          rm -rf private_repo

      - name: Setting up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install project dependencies
        run: npm install

      - name: Configure Proxy
        run: |
          curl -L -o sing-box.tar.gz https://github.com/SagerNet/sing-box/releases/download/v1.13.11/sing-box-1.13.11-linux-amd64.tar.gz
          tar -xzf sing-box.tar.gz
          sudo cp sing-box-1.13.11-linux-amd64/sing-box /usr/local/bin/
          sudo chmod +x /usr/local/bin/sing-box

      - name: Run Automated Inspection
        env:
          SECRETS_JSON: ${{ toJSON(secrets) }}
          GITHUB_REPO: ${{ github.repository }}
        run: npm start

      - name: Record the last run time
        if: always()
        run: |
          echo "Last execution time (UTC): $(date -u +'%Y-%m-%d %H:%M:%S')" > time.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add time.txt
          git commit -m "📝 Update Runtime Records [skip ci]" || echo "No changes; no submission required."
          git push

      - name: Upload screenshots if error
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: debug-screenshots
          path: '*.png'
          retention-days: 5
